#!/bin/bash
# WP-CLI Uninstall Script

# Delete Options
wp option delete 'cmplz_current_datarequest_export_offset'
wp option delete 'cmplz_current_datarequest_export_progress'
wp option delete 'cmplz_datarequest_export_args'
wp option delete 'cmplz_datarequest_file_name'
wp option delete 'cmplz_dnsmpd_db_version'
wp option delete 'cmplz_run_activation'
wp option delete 'cmplz_activation_time'
wp option delete 'cmplz_dismissed_warnings'
wp option delete 'complianz_options_custom-scripts'
wp option delete 'cmplz_post_scribe_required'
wp option delete 'cmplz_wizard_completed_once'
wp option delete 'cmplz_documents_update_date'
wp option delete 'cmplz_publish_date'
wp option delete 'cmplz_update_legal_documents_mail_sent'
wp db query "DELETE FROM wp_options WHERE option_name LIKE '%_custom_page'"
wp db query "DELETE FROM wp_options WHERE option_name LIKE '%_custom_page_url'"
wp option delete 'cmplz_pdf_dir_token'
wp option delete 'cmplz_options'
wp db query "DELETE FROM wp_options WHERE option_name LIKE 'complianz_options_%'"
wp option delete 'cmplz_deleted_cookies'
wp db query "DELETE FROM wp_options WHERE option_name LIKE '%_tour_started'"
wp db query "DELETE FROM wp_options WHERE option_name LIKE '%_tour_shown_once'"
wp option delete 'cmplz_review_notice_shown'
wp option delete 'cmplz_generate_new_cookiepolicy_snapshot'
wp option delete 'cmplz_detected_stats_data'
wp option delete 'cmplz_detected_stats_type'
wp option delete 'cmplz_cookietable_version'
wp option delete 'cmplz_changed_cookies'
wp option delete 'cmplz_synced_cookiedatabase_once'
wp option delete 'cmplz_sync_cookies_complete'
wp option delete 'cmplz_sync_cookies_after_services_complete'
wp option delete 'cmplz_sync_services_complete'
wp option delete 'cmplz_last_cookie_scan'
wp option delete 'cmplz_detected_social_media'
wp option delete 'cmplz_detected_thirdparty_services'
wp option delete 'cmplz_double_stats'
wp option delete 'cmplz_detected_stats'
wp option delete 'cmplz_ssl_verify'
wp option delete 'cmplz_curl_error'
wp option delete 'cmplz_last_cookie_sync'
wp option delete 'cmplz_cookie_data_verified_date'
wp option delete 'cmplz_first_sync_started'
wp option delete 'cmplz_purposes_stored'
wp option delete 'cmplz_servicetypes_stored'
wp db query "DELETE FROM wp_options WHERE option_name LIKE 'cmplz_serviceTypes_%'"
wp option delete 'cmplz_serviceTypes_stored'
wp option delete 'cmplz_detected_console_errors'
wp option delete 'cmplz_excluded_posts_array'
wp option delete 'complianz_active_policy_id'
wp option delete 'qtranslate_enabled_languages'
wp option delete 'trp_settings'
wp option delete 'cmplz_cbdb_version'
wp option delete 'cmplz_tracking_ab_started'
wp option delete 'cmplz_preloaded_privacy_info'
wp option delete 'cmplz_first_version'
wp option delete 'cmplz_transients'
wp option delete 'cmplz_wsc_signup_status'
wp option delete 'cmplz_disabled_placeholders'
wp option delete 'complianz_options_integrations'
wp option delete 'cmplz_detected_forms'
wp option delete 'cmplz_active_integrations'
wp option delete 'cmplz_integrations_changed'
wp option delete 'cmplz_elementor_hub_autogenerated'
wp option delete 'user_registration_login_options_enable_recaptcha'
wp option delete 'woocommerce_google_analytics_settings'
wp option delete 'woocommerce_google_analytics_pro_settings'
wp option delete 'wpgmza_global_settings'
wp option delete 'wpforms_settings'
wp option delete 'cmplz_upgraded_to_7'
wp option delete 'cmplz_onboarding_dismissed'
wp option delete 'cmplz_ajax_fallback_active'
wp option delete 'cmplz_key'
wp option delete 'auto_update_plugins'
wp db query "DELETE FROM wp_options WHERE option_name LIKE '%auto_installed_license'"
wp option delete 'cmplz-current-version'
wp option delete 'complianz_options_wizard'
wp option delete 'cmplz_cookie-statement_custom_page'
wp option delete 'cmplz_privacy-statement_custom_page'
wp option delete 'cmplz_upgraded_to_five'
wp option delete 'complianz_options_settings'
wp option delete 'cmplz_elementor_banner_dropped'
wp option delete 'cmplz_elementor_autogenerated'
wp option delete 'cmplz_license_key'
wp option delete 'cmplz_wsc_scan_status'
wp option delete 'cmplz_wsc_scan_id'
wp option delete 'cmplz_wsc_checks_scan_id'
wp option delete 'cmplz_wsc_scan_createdAt'
wp option delete 'cmplz_wsc_checks_scan_createdAt'
wp option delete 'cmplz_wsc_error_email_not_sent'
wp option delete 'cmplz_wsc_status'
wp option delete 'cmplz_wsc_signup_date'
wp option delete 'cmplz_wsc_error_email_mismatch'
wp option delete 'cmplz_wsc_error_missing_token'
wp option delete 'cmplz_wsc_error_email_auth_failed'
wp option delete 'cmplz_wsc_auth_completed'
wp option delete 'cmplz_wsc_error_token_api'
wp option delete 'cmplz_wsc_connection_updated'
wp db query "DELETE FROM wp_options WHERE option_name LIKE '%_consentdata'"
wp db query "DELETE FROM wp_options WHERE option_name LIKE 'cmplz_consent_error_timestamp_%'"
wp db query "DELETE FROM wp_options WHERE option_name LIKE 'cmplz_consent_error_consentdata_%'"
wp db query "DELETE FROM wp_options WHERE option_name LIKE 'cmplz_consent_%'"
wp option delete 'cmplz_newsletter_signup_error_email'
wp option delete 'cmplz_newsletter_signup_error'
wp option delete 'cmplz_newsletter_signup_error_timestamp'
wp option delete 'cmplz_wsc_logs'
wp option delete 'cmplz_wsc_onboarding_status'
wp option delete 'cmplz_wsc_reset_complete'
wp option delete 'cmplz_wsc_onboarding_dismissed'
wp option delete 'cmplz_wsc_websitescan_dismissed'
wp option delete 'cmplz_wsc_onboarding_complete'
wp option delete 'cmplz_consent_wsc_consent'
wp option delete 'cmplz_wsc_newsletter_dismissed'
wp option delete 'cmplz_wsc_scan_iteration'
wp option delete 'cmplz_wsc_scan_progress'
wp option delete 'cmplz_wsc_scan_first_run'
wp option delete 'cmplz_wsc_checks_scan_polling'
wp option delete 'cmplz_wsc_checks_last_mail_sent'
wp option delete 'cmplz_wsc_checks_last_mail_sent_error'
wp option delete 'cmplz_wsc_user_deletion_temp_credentials'
wp db query "DELETE FROM wp_options WHERE option_name LIKE '%_message'"
wp db query "DELETE FROM wp_options WHERE option_name LIKE '%_timestamp'"

# Delete Transients
wp transient delete 'complianz_warnings'
wp transient delete 'complianz_warnings_admin_notices'
wp db query "DELETE FROM wp_options WHERE option_name LIKE '_transient_complianz_warnings%' OR option_name LIKE '_site_transient_complianz_warnings%'"
wp transient delete 'cmplz_blocked_scripts'
wp db query "DELETE FROM wp_options WHERE option_name LIKE '_transient_%_redirect_to_settings' OR option_name LIKE '_site_transient_%_redirect_to_settings'"
wp transient delete 'rsssl_plugin_download_active'
wp db query "DELETE FROM wp_options WHERE option_name LIKE '_transient_%_plugin_info' OR option_name LIKE '_site_transient_%_plugin_info'"
wp transient delete 'cmplz_wizard_locked_by_user'
wp transient delete 'cmplz_redirect_to_settings_page'
wp transient delete 'cmplz_pages_list'
wp transient delete 'cmplz_processed_pages_list'
wp transient delete 'cmplz_cookiedatabase_request_active'
wp transient delete 'cmplz_cookie_settings_cache'
wp transient delete 'cmplz_checked_for_js_count'
wp transient delete 'cmplz_cookies'
wp transient delete 'cmplz_generate_css_active'
wp transient delete 'cmplz_email_recently_sent'
wp transient delete 'cmplz_plusone_count'
wp transient delete 'cmplz_admin_notices'
wp transient delete 'media_months'
wp transient delete 'cmplz_upgrade_dir'
wp transient delete 'cmplz_wsc_last_cookies'
wp transient delete 'cmplz_wsc_checks_scan_error'
wp transient delete 'cmplz_wsc_last_checks'
wp transient delete 'cmplz_wsc_checks_last_detections'

# Clear Cron Jobs
wp cron event delete 'cmplz_every_week_hook'
wp cron event delete 'cmplz_every_day_hook'
wp cron event delete 'cmplz_every_five_minutes_hook'
wp cron event delete 'cmplz_every_month_hook'
wp cron event delete 'cmplz_schedule_create_wsc_site_id'
wp cron event delete 'cmplz_wsc_checks_retrieve_results'

# Direct DB Queries (Fallback)
wp db query "DELETE FROM wp_postmeta WHERE meta_key = 'cmplz_document_status'"
wp db query "DELETE FROM wp_usermeta WHERE meta_key = 'cmplz_document_status'"
wp db query "DELETE FROM wp_termmeta WHERE meta_key = 'cmplz_document_status'"
wp db query "DELETE FROM wp_commentmeta WHERE meta_key = 'cmplz_document_status'"
wp db query "DELETE FROM wp_postmeta WHERE meta_key = 'cmplz_shortcode'"
wp db query "DELETE FROM wp_usermeta WHERE meta_key = 'cmplz_shortcode'"
wp db query "DELETE FROM wp_termmeta WHERE meta_key = 'cmplz_shortcode'"
wp db query "DELETE FROM wp_commentmeta WHERE meta_key = 'cmplz_shortcode'"
wp db query "DELETE FROM wp_postmeta WHERE meta_key = '_cmplz_scanned_post'"
wp db query "DELETE FROM wp_usermeta WHERE meta_key = '_cmplz_scanned_post'"
wp db query "DELETE FROM wp_termmeta WHERE meta_key = '_cmplz_scanned_post'"
wp db query "DELETE FROM wp_commentmeta WHERE meta_key = '_cmplz_scanned_post'"
wp db query "DELETE FROM wp_postmeta WHERE meta_key = 'cmplz_hide_cookiebanner'"
wp db query "DELETE FROM wp_usermeta WHERE meta_key = 'cmplz_hide_cookiebanner'"
wp db query "DELETE FROM wp_termmeta WHERE meta_key = 'cmplz_hide_cookiebanner'"
wp db query "DELETE FROM wp_commentmeta WHERE meta_key = 'cmplz_hide_cookiebanner'"
wp db query "DELETE FROM wp_postmeta WHERE meta_key = '_thumbnail_id'"
wp db query "DELETE FROM wp_usermeta WHERE meta_key = '_thumbnail_id'"
wp db query "DELETE FROM wp_termmeta WHERE meta_key = '_thumbnail_id'"
wp db query "DELETE FROM wp_commentmeta WHERE meta_key = '_thumbnail_id'"
wp db query "DELETE FROM wp_postmeta WHERE meta_key LIKE '%-eu'"
wp db query "DELETE FROM wp_usermeta WHERE meta_key LIKE '%-eu'"
wp db query "DELETE FROM wp_termmeta WHERE meta_key LIKE '%-eu'"
wp db query "DELETE FROM wp_commentmeta WHERE meta_key LIKE '%-eu'"
