-- WordPress Plugin Uninstall SQL Script

-- Delete Options & Transients
DELETE FROM wp_options WHERE option_name IN ('cmplz_current_datarequest_export_offset', 'cmplz_current_datarequest_export_progress', 'cmplz_datarequest_export_args', 'cmplz_datarequest_file_name', 'cmplz_dnsmpd_db_version', 'cmplz_run_activation', 'cmplz_activation_time', 'cmplz_dismissed_warnings', 'complianz_options_custom-scripts', 'cmplz_post_scribe_required', 'cmplz_wizard_completed_once', 'cmplz_documents_update_date', 'cmplz_publish_date', 'cmplz_update_legal_documents_mail_sent', 'cmplz_pdf_dir_token', 'cmplz_options', 'cmplz_deleted_cookies', 'cmplz_review_notice_shown', 'cmplz_generate_new_cookiepolicy_snapshot', 'cmplz_detected_stats_data', 'cmplz_detected_stats_type', 'cmplz_cookietable_version', 'cmplz_changed_cookies', 'cmplz_synced_cookiedatabase_once', 'cmplz_sync_cookies_complete', 'cmplz_sync_cookies_after_services_complete', 'cmplz_sync_services_complete', 'cmplz_last_cookie_scan', 'cmplz_detected_social_media', 'cmplz_detected_thirdparty_services', 'cmplz_double_stats', 'cmplz_detected_stats', 'cmplz_ssl_verify', 'cmplz_curl_error', 'cmplz_last_cookie_sync', 'cmplz_cookie_data_verified_date', 'cmplz_first_sync_started', 'cmplz_purposes_stored', 'cmplz_servicetypes_stored', 'cmplz_serviceTypes_stored', 'cmplz_detected_console_errors', 'cmplz_excluded_posts_array', 'complianz_active_policy_id', 'qtranslate_enabled_languages', 'trp_settings', 'cmplz_cbdb_version', 'cmplz_tracking_ab_started', 'cmplz_preloaded_privacy_info', 'cmplz_first_version', 'cmplz_transients');
DELETE FROM wp_options WHERE option_name IN ('cmplz_wsc_signup_status', 'cmplz_disabled_placeholders', 'complianz_options_integrations', 'cmplz_detected_forms', 'cmplz_active_integrations', 'cmplz_integrations_changed', 'cmplz_elementor_hub_autogenerated', 'user_registration_login_options_enable_recaptcha', 'woocommerce_google_analytics_settings', 'woocommerce_google_analytics_pro_settings', 'wpgmza_global_settings', 'wpforms_settings', 'cmplz_upgraded_to_7', 'cmplz_onboarding_dismissed', 'cmplz_ajax_fallback_active', 'cmplz_key', 'auto_update_plugins', 'cmplz-current-version', 'complianz_options_wizard', 'cmplz_cookie-statement_custom_page', 'cmplz_privacy-statement_custom_page', 'cmplz_upgraded_to_five', 'complianz_options_settings', 'cmplz_elementor_banner_dropped', 'cmplz_elementor_autogenerated', 'cmplz_license_key', 'cmplz_wsc_scan_status', 'cmplz_wsc_scan_id', 'cmplz_wsc_checks_scan_id', 'cmplz_wsc_scan_createdAt', 'cmplz_wsc_checks_scan_createdAt', 'cmplz_wsc_error_email_not_sent', 'cmplz_wsc_status', 'cmplz_wsc_signup_date', 'cmplz_wsc_error_email_mismatch', 'cmplz_wsc_error_missing_token', 'cmplz_wsc_error_email_auth_failed', 'cmplz_wsc_auth_completed', 'cmplz_wsc_error_token_api', 'cmplz_wsc_connection_updated', 'cmplz_newsletter_signup_error_email', 'cmplz_newsletter_signup_error', 'cmplz_newsletter_signup_error_timestamp', 'cmplz_wsc_logs', 'cmplz_wsc_onboarding_status', 'cmplz_wsc_reset_complete', 'cmplz_wsc_onboarding_dismissed', 'cmplz_wsc_websitescan_dismissed', 'cmplz_wsc_onboarding_complete', 'cmplz_consent_wsc_consent');
DELETE FROM wp_options WHERE option_name IN ('cmplz_wsc_newsletter_dismissed', 'cmplz_wsc_scan_iteration', 'cmplz_wsc_scan_progress', 'cmplz_wsc_scan_first_run', 'cmplz_wsc_checks_scan_polling', 'cmplz_wsc_checks_last_mail_sent', 'cmplz_wsc_checks_last_mail_sent_error', 'cmplz_wsc_user_deletion_temp_credentials', 'complianz_warnings', 'complianz_warnings_admin_notices', 'cmplz_blocked_scripts', 'rsssl_plugin_download_active', 'cmplz_wizard_locked_by_user', 'cmplz_redirect_to_settings_page', 'cmplz_pages_list', 'cmplz_processed_pages_list', 'cmplz_cookiedatabase_request_active', 'cmplz_cookie_settings_cache', 'cmplz_checked_for_js_count', 'cmplz_cookies', 'cmplz_generate_css_active', 'cmplz_email_recently_sent', 'cmplz_plusone_count', 'cmplz_admin_notices', 'media_months', 'cmplz_upgrade_dir', 'cmplz_wsc_last_cookies', 'cmplz_wsc_checks_scan_error', 'cmplz_wsc_last_checks', 'cmplz_wsc_checks_last_detections');
DELETE FROM wp_options WHERE option_name LIKE '%_custom_page';
DELETE FROM wp_options WHERE option_name LIKE '%_custom_page_url';
DELETE FROM wp_options WHERE option_name LIKE 'complianz_options_%';
DELETE FROM wp_options WHERE option_name LIKE '%_tour_started';
DELETE FROM wp_options WHERE option_name LIKE '%_tour_shown_once';
DELETE FROM wp_options WHERE option_name LIKE 'cmplz_serviceTypes_%';
DELETE FROM wp_options WHERE option_name LIKE '%auto_installed_license';
DELETE FROM wp_options WHERE option_name LIKE '%_consentdata';
DELETE FROM wp_options WHERE option_name LIKE 'cmplz_consent_error_timestamp_%';
DELETE FROM wp_options WHERE option_name LIKE 'cmplz_consent_error_consentdata_%';
DELETE FROM wp_options WHERE option_name LIKE 'cmplz_consent_%';
DELETE FROM wp_options WHERE option_name LIKE '%_message';
DELETE FROM wp_options WHERE option_name LIKE '%_timestamp';
DELETE FROM wp_options WHERE option_name LIKE 'complianz_warnings%';
DELETE FROM wp_options WHERE option_name LIKE '%_redirect_to_settings';
DELETE FROM wp_options WHERE option_name LIKE '%_plugin_info';

-- Delete Metadata
DELETE FROM wp_postmeta WHERE meta_key IN ('cmplz_document_status', 'cmplz_shortcode', '_cmplz_scanned_post', 'cmplz_hide_cookiebanner', '_thumbnail_id');
DELETE FROM wp_usermeta WHERE meta_key IN ('cmplz_document_status', 'cmplz_shortcode', '_cmplz_scanned_post', 'cmplz_hide_cookiebanner', '_thumbnail_id');
DELETE FROM wp_termmeta WHERE meta_key IN ('cmplz_document_status', 'cmplz_shortcode', '_cmplz_scanned_post', 'cmplz_hide_cookiebanner', '_thumbnail_id');
DELETE FROM wp_commentmeta WHERE meta_key IN ('cmplz_document_status', 'cmplz_shortcode', '_cmplz_scanned_post', 'cmplz_hide_cookiebanner', '_thumbnail_id');
DELETE FROM wp_postmeta WHERE meta_key LIKE '%-eu';
DELETE FROM wp_usermeta WHERE meta_key LIKE '%-eu';
DELETE FROM wp_termmeta WHERE meta_key LIKE '%-eu';
DELETE FROM wp_commentmeta WHERE meta_key LIKE '%-eu';

