<?php

// If uninstall not called from WordPress, then exit.
if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}

// Delete Options
delete_option('dbanon_config');
delete_site_option('dbanon_config');
delete_option('dbanon_columns');
delete_site_option('dbanon_columns');
delete_option('dbanon_rows');
delete_site_option('dbanon_rows');
delete_option('dbanon_environment');
delete_site_option('dbanon_environment');
delete_option('dbanon_runs');
delete_site_option('dbanon_runs');
delete_option('dbanon_autogenerated');
delete_site_option('dbanon_autogenerated');
delete_option('dbanon_domains');
delete_site_option('dbanon_domains');
delete_option('dbanon_names');
delete_site_option('dbanon_names');
delete_option('dbanon_nicknames');
delete_site_option('dbanon_nicknames');
delete_option('dbanon_agents');
delete_site_option('dbanon_agents');
delete_option('dbanon_ibans');
delete_site_option('dbanon_ibans');
delete_option('dbanon_cities');
delete_site_option('dbanon_cities');
delete_option('dbanon_streets');
delete_site_option('dbanon_streets');
delete_option('dbanon_generated_rules_contact-form-cfdb7_contact-form-cfdb-7');
delete_site_option('dbanon_generated_rules_contact-form-cfdb7_contact-form-cfdb-7');
delete_option('dbanon_generated_rules_flamingo_flamingo');
delete_site_option('dbanon_generated_rules_flamingo_flamingo');
delete_option('dbanon_generated_rules_fluentform_fluentform');
delete_site_option('dbanon_generated_rules_fluentform_fluentform');
delete_option('dbanon_generated_rules_formidable_formidable');
delete_site_option('dbanon_generated_rules_formidable_formidable');
delete_option('dbanon_generated_rules_forminator_forminator');
delete_site_option('dbanon_generated_rules_forminator_forminator');
delete_option('dbanon_generated_rules_ninjaforms_ninjaforms');
delete_site_option('dbanon_generated_rules_ninjaforms_ninjaforms');
delete_option('dbanon_generated_rules_woocommerce_woocommerce');
delete_site_option('dbanon_generated_rules_woocommerce_woocommerce');
delete_option('dbanon_generated_rules_wordpress_core');
delete_site_option('dbanon_generated_rules_wordpress_core');
delete_option('dbanon_generated_rules_wp_user_avatar_wp_user_avatar');
delete_site_option('dbanon_generated_rules_wp_user_avatar_wp_user_avatar');
delete_option('fs_debug_mode');
delete_site_option('fs_debug_mode');
delete_option('_transient_timeout_fs_snooze_period');
delete_site_option('_transient_timeout_fs_snooze_period');
delete_option('_site_transient_timeout_fs_snooze_period');
delete_site_option('_site_transient_timeout_fs_snooze_period');
delete_option('active_sitewide_plugins');
delete_site_option('active_sitewide_plugins');
delete_option('fs_storage_logger');
delete_site_option('fs_storage_logger');
delete_option('fs_active_plugins');
delete_site_option('fs_active_plugins');

// Delete Transients
delete_transient('fs_snooze_period');
delete_site_transient('fs_snooze_period');
delete_transient('update_plugins');
delete_site_transient('update_plugins');
delete_transient('_fs_api_connection_retry_counter');
delete_site_transient('_fs_api_connection_retry_counter');
delete_transient('update_themes');
delete_site_transient('update_themes');

// Clear Cron Jobs
wp_clear_scheduled_hook('fs_debug_turn_off_logging_hook');

