#!/bin/bash
# WP-CLI Uninstall Script

# Delete Options
wp option delete 'dbanon_config'
wp option delete 'dbanon_columns'
wp option delete 'dbanon_rows'
wp option delete 'dbanon_environment'
wp option delete 'dbanon_runs'
wp option delete 'dbanon_autogenerated'
wp option delete 'dbanon_domains'
wp option delete 'dbanon_names'
wp option delete 'dbanon_nicknames'
wp option delete 'dbanon_agents'
wp option delete 'dbanon_ibans'
wp option delete 'dbanon_cities'
wp option delete 'dbanon_streets'
wp option delete 'dbanon_generated_rules_contact-form-cfdb7_contact-form-cfdb-7'
wp option delete 'dbanon_generated_rules_flamingo_flamingo'
wp option delete 'dbanon_generated_rules_fluentform_fluentform'
wp option delete 'dbanon_generated_rules_formidable_formidable'
wp option delete 'dbanon_generated_rules_forminator_forminator'
wp option delete 'dbanon_generated_rules_ninjaforms_ninjaforms'
wp option delete 'dbanon_generated_rules_woocommerce_woocommerce'
wp option delete 'dbanon_generated_rules_wordpress_core'
wp option delete 'dbanon_generated_rules_wp_user_avatar_wp_user_avatar'
wp option delete 'fs_debug_mode'
wp option delete '_transient_timeout_fs_snooze_period'
wp option delete '_site_transient_timeout_fs_snooze_period'
wp option delete 'active_sitewide_plugins'
wp option delete 'fs_storage_logger'
wp option delete 'fs_active_plugins'

# Delete Transients
wp transient delete 'fs_snooze_period'
wp transient delete 'update_plugins'
wp transient delete '_fs_api_connection_retry_counter'
wp transient delete 'update_themes'

# Clear Cron Jobs
wp cron event delete 'fs_debug_turn_off_logging_hook'

