<?php

namespace WPUninstaller;

class BashGenerator {

    /**
     * Generates a Bash script using WP-CLI commands to uninstall plugin data.
     * 
     * @param array $findings Data from PluginAnalyzer
     * @return string Valid Bash script string for uninstall.sh
     */
    public function generate(array $findings): string {
        $bash = "#!/bin/bash\n\n";
        $bash .= "# Uninstall script automatically generated by WP Uninstaller.\n";
        $bash .= "# This script uses WP-CLI to remove plugin remnants from the database.\n";
        $bash .= "# Run this script in the root directory of your WordPress installation.\n\n";
        $bash .= "echo \"Starting uninstallation process via WP-CLI...\"\n\n";

        // Options
        if (!empty($findings['options'])) {
            $bash .= "# Delete Options\n";
            foreach ($findings['options'] as $option) {
                $escaped = escapeshellarg($option);
                // We use 'delete' and ignore errors if the option doesn't exist.
                $bash .= "wp option delete {$escaped} >/dev/null 2>&1 || true\n";
            }
            $bash .= "\n";
        }

        // Transients
        if (!empty($findings['transients'])) {
            $bash .= "# Delete Transients\n";
            foreach ($findings['transients'] as $transient) {
                $escaped = escapeshellarg($transient);
                $bash .= "wp transient delete {$escaped} >/dev/null 2>&1 || true\n";
            }
            $bash .= "\n";
        }

        // Metadata
        if (!empty($findings['metadata'])) {
            $bash .= "# Delete Metadata is complex via WP-CLI base commands because it requires object IDs.\n";
            $bash .= "# Alternatively, WP-CLI provides `wp db query`.\n";
            foreach ($findings['metadata'] as $meta) {
                $escapedKey = addslashes($meta); // for SQL inside bash
                $bash .= "wp db query \"DELETE FROM \\\$(wp db prefix)postmeta WHERE meta_key = '{$escapedKey}';\" >/dev/null 2>&1 || true\n";
                $bash .= "wp db query \"DELETE FROM \\\$(wp db prefix)usermeta WHERE meta_key = '{$escapedKey}';\" >/dev/null 2>&1 || true\n";
                $bash .= "wp db query \"DELETE FROM \\\$(wp db prefix)commentmeta WHERE meta_key = '{$escapedKey}';\" >/dev/null 2>&1 || true\n";
                $bash .= "wp db query \"DELETE FROM \\\$(wp db prefix)termmeta WHERE meta_key = '{$escapedKey}';\" >/dev/null 2>&1 || true\n";
            }
            $bash .= "\n";
        }

        // Cron Jobs
        if (!empty($findings['cron_jobs'])) {
            $bash .= "# Clear Scheduled Hooks\n";
            foreach ($findings['cron_jobs'] as $hook) {
                $escaped = escapeshellarg($hook);
                $bash .= "wp cron event delete {$escaped} >/dev/null 2>&1 || true\n";
            }
            $bash .= "\n";
        }

        // Custom Tables
        if (!empty($findings['custom_tables'])) {
            $bash .= "# Drop Custom Tables\n";
            foreach ($findings['custom_tables'] as $table) {
                if (strpos($table, '{wpdb_prefix}') !== false) {
                    $tableName = str_replace('{wpdb_prefix}', '', $table);
                    $bash .= "wp db query \"DROP TABLE IF EXISTS \\\$(wp db prefix)" . addslashes($tableName) . "\" >/dev/null 2>&1 || true\n";
                } else {
                    $escaped = addslashes($table);
                    $bash .= "wp db query \"DROP TABLE IF EXISTS {$escaped}\" >/dev/null 2>&1 || true\n";
                }
            }
            $bash .= "\n";
        }
        
        $bash .= "# Clear Cache\n";
        $bash .= "wp cache flush\n\n";
        $bash .= "echo \"Uninstallation complete.\"\n";

        return $bash;
    }
}
