<?php

namespace WPUninstaller;

class SqlGenerator {

    /**
     * Generates raw SQL commands to uninstall plugin data.
     * Note: Assumes a default '$wpdb->prefix' of 'wp_' for simplicity,
     * but users might need to find/replace 'wp_' depending on their setup.
     * Also, Cron Jobs are serialized in a single 'cron' option, so raw SQL
     * cannot easily remove a single cron hook safely. We skip cron jobs in SQL.
     * 
     * @param array $findings Data from PluginAnalyzer
     * @return string Valid SQL string for uninstall.sql
     */
    public function generate(array $findings): string {
        $prefix = 'wp_'; // Default placeholder prefix
        $sql = "-- Uninstall script automatically generated by WP Uninstaller.\n";
        $sql .= "-- NOTE: Ensure the table prefix '{$prefix}' matches your database.\n\n";

        // Options
        if (!empty($findings['options'])) {
            $sql .= "-- Delete Options\n";
            $escapedOptions = array_map(function($opt) {
                return "'" . addslashes($opt) . "'";
            }, $findings['options']);
            
            // Delete in batches or as one big IN clause
            $optionsList = implode(",\n    ", $escapedOptions);
            $sql .= "DELETE FROM {$prefix}options WHERE option_name IN (\n    {$optionsList}\n);\n\n";
        }

        // Transients
        if (!empty($findings['transients'])) {
            $sql .= "-- Delete Transients\n";
            $escapedTransients = [];
            $escapedTransientTimeouts = [];
            foreach ($findings['transients'] as $transient) {
                $escapedTransients[] = "'_transient_" . addslashes($transient) . "'";
                $escapedTransientTimeouts[] = "'_transient_timeout_" . addslashes($transient) . "'";
            }
            
            $transientsList = implode(",\n    ", array_merge($escapedTransients, $escapedTransientTimeouts));
            $sql .= "DELETE FROM {$prefix}options WHERE option_name IN (\n    {$transientsList}\n);\n\n";
        }

        // Metadata
        if (!empty($findings['metadata'])) {
            $sql .= "-- Delete Metadata (from common tables: postmeta, usermeta, commentmeta, termmeta)\n";
            $escapedMeta = array_map(function($meta) {
                return "'" . addslashes($meta) . "'";
            }, $findings['metadata']);
            $metaList = implode(",\n    ", $escapedMeta);
            
            $sql .= "DELETE FROM {$prefix}postmeta WHERE meta_key IN (\n    {$metaList}\n);\n";
            $sql .= "DELETE FROM {$prefix}usermeta WHERE meta_key IN (\n    {$metaList}\n);\n";
            $sql .= "DELETE FROM {$prefix}commentmeta WHERE meta_key IN (\n    {$metaList}\n);\n";
            $sql .= "DELETE FROM {$prefix}termmeta WHERE meta_key IN (\n    {$metaList}\n);\n\n";
        }

        // Custom Tables
        if (!empty($findings['custom_tables'])) {
            $sql .= "-- Drop Custom Tables\n";
            foreach ($findings['custom_tables'] as $table) {
                if (strpos($table, '{wpdb_prefix}') !== false) {
                    $tableName = str_replace('{wpdb_prefix}', $prefix, $table);
                    $sql .= "DROP TABLE IF EXISTS `" . addslashes($tableName) . "`;\n";
                } else {
                    $sql .= "DROP TABLE IF EXISTS `" . addslashes($table) . "`;\n";
                }
            }
            $sql .= "\n";
        }

        return $sql;
    }
}
