<?php

namespace WPUninstaller;

class UninstallGenerator {

    /**
     * Generates the PHP code for an uninstall.php file.
     * 
     * @param array $findings Data from PluginAnalyzer
     * @return string Valid PHP string for uninstall.php
     */
    public function generate(array $findings): string {
        $php = "<?php\n\n";
        $php .= "/**\n * Uninstall script automatically generated by WP Uninstaller.\n */\n\n";
        $php .= "// If uninstall not called from WordPress, then exit.\n";
        $php .= "if (!defined('WP_UNINSTALL_PLUGIN')) {\n";
        $php .= "    exit;\n";
        $php .= "}\n\n";

        // Options
        if (!empty($findings['options'])) {
            $php .= "// Delete Options\n";
            foreach ($findings['options'] as $option) {
                // Ensure $option literal is safe to print
                $escaped = addslashes($option);
                $php .= "delete_option('{$escaped}');\n";
                $php .= "delete_site_option('{$escaped}');\n";
            }
            $php .= "\n";
        }

        // Transients
        if (!empty($findings['transients'])) {
            $php .= "// Delete Transients\n";
            foreach ($findings['transients'] as $transient) {
                $escaped = addslashes($transient);
                $php .= "delete_transient('{$escaped}');\n";
                $php .= "delete_site_transient('{$escaped}');\n";
            }
            $php .= "\n";
        }

        // Metadata
        if (!empty($findings['metadata'])) {
            $php .= "// Delete Metadata (across all types)\n";
            // We don't know the exact meta_type, so we might need to delete from common ones
            foreach ($findings['metadata'] as $meta) {
                 $escaped = addslashes($meta);
                 $php .= "\$meta_types = ['post', 'user', 'comment', 'term'];\n";
                 $php .= "foreach (\$meta_types as \$type) {\n";
                 $php .= "    delete_metadata(\$type, 0, '{$escaped}', '', true);\n";
                 $php .= "}\n";
            }
            $php .= "\n";
        }

        // Cron Jobs
        if (!empty($findings['cron_jobs'])) {
            $php .= "// Clear Scheduled Hooks\n";
            foreach ($findings['cron_jobs'] as $hook) {
                $escaped = addslashes($hook);
                $php .= "wp_clear_scheduled_hook('{$escaped}');\n";
            }
            $php .= "\n";
        }

        // Custom Tables
        if (!empty($findings['custom_tables'])) {
            $php .= "// Drop Custom Tables\n";
            $php .= "global \$wpdb;\n";
            foreach ($findings['custom_tables'] as $table) {
                // If the table uses the $wpdb->prefix placeholder
                if (strpos($table, '{wpdb_prefix}') !== false) {
                    $tableExpr = "{\$wpdb->prefix}" . addslashes(str_replace('{wpdb_prefix}', '', $table));
                    $php .= "\$wpdb->query(\"DROP TABLE IF EXISTS {$tableExpr}\");\n";
                } else {
                    $escaped = addslashes($table);
                    $php .= "\$wpdb->query(\"DROP TABLE IF EXISTS {$escaped}\");\n";
                }
            }
            $php .= "\n";
        }
        
        // Final flush
        $php .= "// Clear Cache\n";
        $php .= "wp_cache_flush();\n";

        return $php;
    }
}
